COMMANDDIR := command

$(OBJDIR)/gfp_command_factory.o: $(COMMANDDIR)/gfp_command_factory.cc
	$(CC) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/gfp_command.o: $(COMMANDDIR)/gfp_command.cc 
	$(CC) $(CFLAGS) -c -o $@ $<


