PAINTINGDIR := painting

$(OBJDIR)/gfp_drawing_board.o: $(PAINTINGDIR)/gfp_drawing_board.cc
	$(CC) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/gfp_pen.o: $(PAINTINGDIR)/gfp_pen.cc
	$(CC) $(CFLAGS) -c -o $@ $<

$(OBJDIR)/gfp_painting.o: $(PAINTINGDIR)/gfp_painting.cc
	$(CC) $(CFLAGS) -c -o $@ $<

